### ISSUE TITLE
Readme to build kernel an apply patch from upstream

### ISSUE THREAD

**Issue by VictorRodriguez** [includeproject/linux_performance_analysis#1]
Please create a README to build the linux kernel and install it on your host OS
Please craete a README to apply a patch from a mailing list and re build the kernel

**Comment by OIMA** [comment]
Ok. We got it. We will start with this part.

**Comment by AntulioJonathan** [comment]
you want us to commit to the README's?
and if so, what name you want to have in the repo?

**Comment by VictorRodriguez** [comment]
yes , please create a nice and structurated README: 
ie: 
https://www.drupal.org/node/2181737

YOu also have a wiki here , in case you need it

**Comment by VictorRodriguez** [comment]
I was just about to close this bug after the pull request, however I see alack of information on the readme.patch , what about GIT ? patch is just a standard command but you also have options like git am or git apply and so on.. 

In terms of kernel compilaton : 
1) you really just need make and tar to build the kernel , what about gcc , bitnutils ... ? 
2) What is the diference betwen the bzimage and the uimage ? what is lilo ? 

I think is a great start but we need more, if you truly follow these instruction is fine, but think in a way that everyone can follow even your small brother :) 

For future references please check this book , one of the best books to start 

http://www.amazon.com/Embedded-Linux-Primer-Practical-Real-World/dp/0131679848#reader_0131679848

Abraham will be in charg of these bug, we will close as soon as we get a really god documentation either here or in the wiki ( you also have the wiki use it ) 

I know documentatin can be a pain but , it will help in the future for yoru friends and colleges ( yes this is not a school project , is reall project and in real projects the documentation is necesary )

**Comment by AntulioJonathan** [comment]
ouch!!, this is true Victor, must work more and every time better and better, thanks for the feedback

**Comment by richo-mx** [comment]
Maybe this small article can help: http://www.developer.com/open/how-to-start-contributing-to-open-source.html

**Comment by VictorRodriguez** [comment]
This needs more improvment will move to next release V0.2

**Comment by VictorRodriguez** [comment]
Fixed with this https://github.com/includeproject/linux_performance_analysis/blob/master/README.apply_patch.md
Other README also improved 

Thanks @OIMA
