### ISSUE TITLE
linux_performance_analysis/web_scripts/Linux_performance_tests_page/ DIRTY

### ISSUE THREAD

**Issue by VictorRodriguez** [includeproject/linux_performance_analysis#12]
Hi @OIMA 

I was checking the web scripts and: 

1) They do not have a README
2) Can they be automated ( fi so include a Make or script or something ) . The idea is that if server is down we just need to download linux_performance_analysis and run make or ./run.sh or soemthing that README explain 
3) Why do we need directory names like Lucy/Maria ( I dont remember the names ) and so on ? 

Please try to keep the repo as cleen as posible

**Comment by OIMA** [comment]
Ok, do not worry, I will make a script or make file for automize the installation and purge the directories.

**Comment by xe1gyq** [comment]
Is it possible we can have the IP address of the server posted under our Wiki?

**Comment by OIMA** [comment]
I am sorry **xe1gyq**. We are having some problems with the internal network, but the ip should be still alive. I am working on that.

**Comment by xe1gyq** [comment]
No need to sorry OIMA :) please take your time

**Comment by OIMA** [comment]
Yes, you can now post the ip under the wiki. Here is the address again http://148.233.65.226/Linux_performance_tests_page/
The site is not ready yet, but it will be soon.

Regards.

**Comment by richo-mx** [comment]
@OIMA You guys are awesome !!, I'll post the IP to the wiki very soon, just let me write down first some ideas about general framework requirements.

**Comment by OIMA** [comment]
We are using a basic LAMP server. We will bind php with linux shell to run all scripts. Do you have any suggestion for us?

**Comment by VictorRodriguez** [comment]
The web page is not working , since there I will move this to 0.2 and tested next week. I know is not your problem guys but if we go public this can not happend :+1:

**Comment by VictorRodriguez** [comment]
Works
