### ISSUE TITLE
Wiki: High Level Framework Architecture

### ISSUE THREAD

**Issue by xe1gyq** [includeproject/linux_performance_analysis#13]
It is important to have a high level view of the framework architecture for people joining the project to easily understand the big pieces

**Comment by richo-mx** [comment]
I was just going to upload that today....

**Comment by xe1gyq** [comment]
Thanks richo-mx!

**Comment by richo-mx** [comment]
@xe1gyq Just give me a time to breath !, since it is not my core activity :palm_tree:

**Comment by xe1gyq** [comment]
:) I am on vacations Sir @richo-mx ! Take your time!

**Comment by richo-mx** [comment]
@xe1gyq I'm not :( I need some vacations he he

**Comment by VictorRodriguez** [comment]
@xe1gyq and @richo-mx if you want I can upload it , just send a picture of it and I pass it to "nice" diagram

**Comment by richo-mx** [comment]
@VictorRodriguez @xe1gyq I'll upload the diagram very soon :)

**Comment by VictorRodriguez** [comment]
@richo-mx where did you leave the diagram ? I know you update it .. I just dont know where did you leave it

**Comment by VictorRodriguez** [comment]
I love this info https://github.com/includeproject/linux_performance_analysis/wiki/GNU---Linux---Performance-Analysis-Architecture

**Comment by xe1gyq** [comment]
+1
