### ISSUE TITLE
Framework: Core Language

### ISSUE THREAD

**Issue by xe1gyq** [includeproject/linux_performance_analysis#14]
Are we having shell scripting as the default programming language for this project?
Have we discussed about including python?

**Comment by richo-mx** [comment]
@xe1gyq Not yet, Python is quite useful, if you like we can start a discussion over here about it. I don't have any problems if we change to a different tool, however all of us have to be in sync to avoid missunderstandings and future waste of time / reworks.

**Comment by xe1gyq** [comment]
Ok, Let's keep Shell scripting then...

**Comment by richo-mx** [comment]
@xe1gyq we love Python too, since we can do a more modular tool

**Comment by VictorRodriguez** [comment]
I will close this , since is not an issue regards

**Comment by xe1gyq** [comment]
:)
