### ISSUE TITLE
Framework: Tarballs Vs Git Repositories

### ISSUE THREAD

**Issue by xe1gyq** [includeproject/linux_performance_analysis#15]
Today our main packages as the Linux Kernel or LTP uses source code in the form of tarballs. Have we talked about using git repositories to easily pull the latest version instead of downloading the whole package + advantages as going to a specific version?

**Comment by richo-mx** [comment]
If we do so, we need to start pushing our changes to such projects in order to have all data in the GIT repository, however I beleive, must of the changes will be made to personalize according to our needs, what do you thing @xe1gyq ?

**Comment by xe1gyq** [comment]
Do we have specific changes for each of those projects?

**Comment by richo-mx** [comment]
@xe1gyq not at this point :(

**Comment by VictorRodriguez** [comment]
I will close this for two reasons : 
1) LTP  / Linux Kernel and other are tools we use, we only get the latest and stable repository for testing porpose. 
2) If we have patches that improve these projects we will send them to the specific mailing list for the discussion , this git repository is just for the tool

**Comment by xe1gyq** [comment]
I believe it is better to have git repos instead of defined versions
