### ISSUE TITLE
Framework: Package Installation Update

### ISSUE THREAD

**Issue by xe1gyq** [includeproject/linux_performance_analysis#18]
Oscar, can you please help us update scripts/installation_packages to include the following packages:
- byson
- byacc
- flex
- m4
- make

The changes needed are under the "Scripts Variables" section and under "TarBallAll" function.
 https://github.com/includeproject/linux_performance_analysis/blob/master/scripts/install_packages.sh

**Comment by VictorRodriguez** [comment]
What if we use autotools with a configure file ? 
We will be running on multiple distros and it will be a nightmare to install by ourselfs all the dependencies and configurations 

./configure ( will check that all the packages be installed if not a error will came ) [either server or client]
make will build ( if something is needed ) 
make install  ( install all the scripts and tool where it should be ) 

What do you think ?

**Comment by richo-mx** [comment]
I was talking with Victor about autotools, but if you give some time I would like to clarify the full usage of the performance analysis framework, just to clarify :)

**Comment by xe1gyq** [comment]
@VictorRodriguez install_packages.sh check if you have apt-get installed to have a easy installation of the required tools, if not, then it will download and run configure && make & make install for those packages
Please confirm if this is what you are expecting?

@richo-mx I'll wait...

**Comment by richo-mx** [comment]
@xe1gyp as a first step, the script description is as you mention, maybe in near future will require to move to a more robust way that might be autotools.

Please let me know your thoughts

**Comment by VictorRodriguez** [comment]
@richo-mx and @xe1gyq  I am going to do the first realease this friday ( v 0.1 ). All the bugs that are not closed will be moved to 0.2 release, no presure just saying . Thanks a lot to all for all the time and effort.  Happy to spend time on free time on this project

**Comment by richo-mx** [comment]
@VictorRodriguez , Excellent !, i'm ok with the release, and sure, we can move for the next one the remaining ones, do you require something specific in order to move the open issues to the next release ? 

Any additional comment @xe1gyq ? 

Cheers !
xe1gyp :)

**Comment by VictorRodriguez** [comment]
@xe1gyq : 

@VictorRodriguez install_packages.sh check if you have apt-get installed to have a easy installation of the required tools, if not, then it will download and run configure && make & make install for those packages

What about RPM base systems ? fedora ? We need to deliver just with autotools that seems fair for the rest of the distributions . If we get married with just one distro ( apt-get ) is going to be harder to be accepted by the comunity in the future

**Comment by richo-mx** [comment]
@VictorRodriguez Do you want to assign someone to start doing the RPM ?

**Comment by VictorRodriguez** [comment]
@richo-mx not right now .. first lets focus on just fix bugs and make it stable as possible

**Comment by xe1gyq** [comment]
I need to understand about autotools, seems to be a complex transition

**Comment by VictorRodriguez** [comment]
Complex but not complicated :)

**Comment by VictorRodriguez** [comment]
I think is fixed here https://github.com/includeproject/linux_performance_analysis/blob/master/scripts/install_packages.sh
if no please correct me

**Comment by xe1gyq** [comment]
Fixed means this script is using it? Lets have a talk because i am not sure i am getting it including the fact that we are using fixed versions which cause me some mental disorders :)
