### ISSUE TITLE
Read an implement LTP

### ISSUE THREAD

**Issue by VictorRodriguez** [includeproject/linux_performance_analysis#2]
Read documentation and run LTP

https://linux-test-project.github.io/

Make it run on any HW you have ( server/desktop /embedded )

**Comment by martinsillo** [comment]
ok, i support and i try it

**Comment by jglezt** [comment]
I have already installed LTP and I had run the "runalltestsripts". To anyone which still have not installed LTP, I leave a brief summary to how install LTP.

The required packages are: make, bison, yacc, flex, automake, autoconf.

1.- Download the newest version form here http://sourceforge.net/projects/ltp/files/LTP%20Source/
2.- Untar the archive

To configure the package using autoconf:

3.-On the terminal, go to the folder and put the following commands
$make autotools
$ test -d “$(pwd)” || mkdir -p “$(pwd)”
$cd “$(pwd)” && “$(pwd)/configure”

To compile and install the package: 

4.- On the terminal, execute the following commands
$make all
(If you are using a non-root user)
$sudo make SKIP_IDCHECK=1 install

And thats all, if you want to now if the installation were successful, run the “runalltest” script which is located on the installation directory.

**Comment by VictorRodriguez** [comment]
Please upload the wiki to track this info

**Comment by VictorRodriguez** [comment]
Also , this are commands , how can I know that you have run this into your  server/embedded-platfrom or desktop ? 

We need to : 
1) Automate this process ( bash/python/what ever you want -  script )
2) Publish the results on a web page 

Do you think that will be useful to create an image with the architecture design of the entire system?

**Comment by jglezt** [comment]
Ok, I will make the script as soon as possible :)

**Comment by richo-mx** [comment]
Closing this issue since LTP is already  implemented.
