### ISSUE TITLE
Implement Power Top

### ISSUE THREAD

**Issue by VictorRodriguez** [includeproject/linux_performance_analysis#3]
Read 

https://01.org/powertop

Implement on the same HW that you have LTP 

Publish the results in a we page ( hosted on any server you want )

**Comment by jglezt** [comment]
In Debian 8, powertop 2.6 is installed by default.
I will send the test results from both LTP and PowerTop to OIMA so he upload them on the server

**Comment by VictorRodriguez** [comment]
OK debian is fine, what If I had another OS ? 

Why dont you create a script that: 
1) Download 
2) Install
3) Verify installation 

We need to think more about autoamtion and also that we will be a public service we need to suport multiple OS , tools , patches . 

We also need to publish the results of this in a wb page upon demand by the user . 

I think that a full pictuore of what we need to do is going to be better :)

**Comment by VictorRodriguez** [comment]
What is OIMA ??

**Comment by Lucerin** [comment]
Oscar ivan martinez Arce

**Comment by OIMA** [comment]
You can check some results of ltp tests and powertop on this web page [Linux_performance_tests_page](http://148.233.65.226/Linux_performance_tests_page/index.html). We are working on powertop on demand by the user so you will be able to calculate the server performance in real time.

**Comment by richo-mx** [comment]
Hi all, first of all seems like all of you have been done some good job. However i'll start uploading some specific tasks for any person interested, this to give more shape and meaning to all data. By itself the numbers doesn't mean anything, and are boring to read all the log files, specially the LTP ones :), so if you are interested, keep an eye on the future tasks to be posted.

**Comment by OIMA** [comment]
Ok, we will be aware of any publication you post. You are right, numbers are boring and perhaps senseless. If you are more specific with the tasks we shall cover them in a better way. Thank you!

**Comment by richo-mx** [comment]
Thanks @OIMA, keep an eye on the future issues. Meanwhile i'm going to close this one, since Power Top is already implemented.
