### ISSUE TITLE
Create script to download , install and run power top 

### ISSUE THREAD

**Issue by VictorRodriguez** [includeproject/linux_performance_analysis#5]
To configure the package using autoconf:

3.-On the terminal, go to the folder and put the following commands
$make autotools
$ test -d “$(pwd)” || mkdir -p “$(pwd)”
$cd “$(pwd)” && “$(pwd)/configure”

To compile and install the package:

4.- On the terminal, execute the following commands
$make all
(If you are using a non-root user)
$sudo make SKIP_IDCHECK=1 install

**Comment by richo-mx** [comment]
Can we close this issue ? Are any work still in progress ?

**Comment by OIMA** [comment]
We don't have it yet, but Lucero is working on this.

**Comment by richo-mx** [comment]
Nice, once you or her have some news about this issue, please don't hesitate to post it here :)

**Comment by richo-mx** [comment]
@Lucerin , as soon as you  have something to post / upload to the repo, feel free to do so.

**Comment by richo-mx** [comment]
@OIMA , Is there any comment about this issue ? can we close it ?

**Comment by OIMA** [comment]
This issue was covered by @Lucerin, but she made it on my fork. I will make the pull request with this script and some other changes soon. You can close the issue if you want.

**Comment by VictorRodriguez** [comment]
@OIMA I will close this isue, since this is working on the web page
