### ISSUE TITLE
Add html code of  Linux_performance_tests_page

### ISSUE THREAD

**Issue by VictorRodriguez** [includeproject/linux_performance_analysis#6]
The  Linux_performance_tests_page ( http://148.233.65.226/Linux_performance_tests_page/) is a great web page , however this will be a tool , and it shoudl be able to being deployed to any other computter :) . What happen if a dinosoure attack the lab where this great web page is hosted ? ok we buy another server ( sure, as easy as asking for one :) ) and then we install what ?? Do you agree with this ? always keep in mind to save your knowledge and code for the future

**Comment by OIMA** [comment]
I agree Víctor, I did not know that we could need the page for the project's aim. But we made an extra repository with the source code. The code will be available as soon as possible. Consider it done.

**Comment by OIMA** [comment]
You can check the source code of [Linux_performance_tests_page](https://github.com/OIMA/Linux_performance_tests_page). Please tell me if you want to merge this with linux_performance_analysis.

**Comment by VictorRodriguez** [comment]
Merge this as part of the linux performance tool as web_scripts directory

**Comment by OIMA** [comment]
I did merge the web page at web_scripts directory, the same server would be used for future tests. 

Regards.
