### ISSUE TITLE
Add capability to upload any patch ( or series of patch ) 

### ISSUE THREAD

**Issue by VictorRodriguez** [includeproject/linux_performance_analysis#7]
Ok here is the heart of the tool. Right now the tool is capable of run the LTP and Power Top ( more tools being added on the way ) but the real core of this tool will be .. Any one should be able to upload their patches to test them without worry about the test suite ( LTP/Power Top / etc ) and the server/ client side ( we will create the infrastructure to support clients , but thats another feature , not for this milestone ) . The results should presnet the results after and before the patch. The patch will be compiled against the latest stable kernel ( yes thats our golden rule :) ) 

What do you think ?

**Comment by OIMA** [comment]
It sounds amazing, seems like we are closing to the goal, but we are just starting.
I have some questions about this issue.
We will install the kernel 3.19(latest release) on the server or our machines, is it correct?
What do you mean with series of patch? 
I wonder if these series will be sent in the same request and by the same client.
Are we going to apply each patch on the server and throw the results on the page?

Thank you!

**Comment by jglezt** [comment]
Once the user have tested his patch, the server have to revert the changes and go back to the clean kernel?  I will soon upload the results of this issue. Greetings.

**Comment by VictorRodriguez** [comment]
HI 
Sorry for the delay , her are the answers: 
@OIMA 
We will install the kernel 3.19(latest release) on the server or our machines, is it correct?
[Answer] Correct
What do you mean with series of patch?
[Answer] http://rypress.com/tutorials/git/patch-workflows
[Answer] you can have 1 or many .patch files ( all in order 001-100 )
I wonder if these series will be sent in the same request and by the same client.
[Answer] Will be sent to the server ( like upload a picture on facebook )
Are we going to apply each patch on the server and throw the results on the page?
[Answer] Thats the big idea :) 

@helojagt 

Once the user have tested his patch, the server have to revert the changes and go back to the clean kernel? 
[Answer] Yes , I am thinking that it will require a huge security ( we don't know what kind of patches we will receive 
I will soon upload the results of this issue. Greetings.

Great :) good job

**Comment by OIMA** [comment]
Thanks a lot Víctor. Now everything is clear as water. We will upload this feature soon.

**Comment by richo-mx** [comment]
@all please keep it up the hard and well done work !!!

**Comment by VictorRodriguez** [comment]
Works
