### ISSUE TITLE
Fio implementation

### ISSUE THREAD

**Issue by richo-mx** [includeproject/linux_performance_analysis#8]
Hi guys, we have implemented in a successful way: PowerTOP and LTP, however this is not the end of the performance analysis journey.

The next step is to download and get it working FIO, I have already uploaded the FIO version 2.1.10

fio is an I/O tool meant to be used both for benchmark and stress/hardware verification. It has support for 19 different types of I/O engines (sync, mmap, libaio, posixaio, SG v3, splice, null, network, syslet, guasi, solarisaio, and more), I/O priorities (for newer Linux kernels), rate I/O, forked or threaded jobs, and much more. It can work on block devices as well as files. fio accepts job descriptions in a simple-to-understand text format. Several example job files are included. fio displays all sorts of I/O performance information, including complete IO latencies and percentiles. Fio is in wide use in many places, for both benchmarking, QA, and verification purposes. It supports Linux, FreeBSD, NetBSD, OpenBSD, OS X, OpenSolaris, AIX, HP-UX, Android, and Windows.

Tasks:
- Generate "Per-job latency logs"
- Generate "Per-job bandwidth logs" 
- Execute cpuclock-test
- Use the --debug option and dump as many information as you can in your current systems
- All result should be shown here:

http://148.233.65.226/Linux_performance_tests_page/

**Comment by jglezt** [comment]
I have already implemented Fio on my machine, and also made a simple script to install Fio on any GNU/Linux distribution and a script to do all the tests described on this issue. I didn't make the wiki page for both scripts, but i will make them pretty soon. Greetings.

**Comment by richo-mx** [comment]
Nice, please upload the script to the proper section :)

**Comment by richo-mx** [comment]
@helojagt Do we have the results posted in your server infrastructure ?

**Comment by jglezt** [comment]
I already send them to Oscar. I made  push to his repository 4 days ago, for now both of us are working whit the implementation of the patch system on the server, so probably that was the reason for the delay. Greetings

**Comment by richo-mx** [comment]
@helojagt Nice !, so as soon as you have the results posted, please let us know

**Comment by richo-mx** [comment]
@helojagt Can we close this issue ? is already the work done ?

**Comment by OIMA** [comment]
Yes, it is done. The public address is not responding as well as expected but you can see the results there.

**Comment by VictorRodriguez** [comment]
@richo-mx I will move this to 0.1 milestone , just to keep coherency on the milestones ( cosmetic change ) and delete all the others milestones , just to have pure V0.\* milestones

**Comment by richo-mx** [comment]
@OIMA, yes i'm not able to see anything on the web server :(. @VictorRodriguez I'm ok to move this to  next milestone :)

**Comment by VictorRodriguez** [comment]
Verified that runs, will open a new bg to validate consitency of results, but for me this works
