### ISSUE TITLE
Fio visualizer enabling.

### ISSUE THREAD

**Issue by richo-mx** [includeproject/linux_performance_analysis#9]
Hi team,

As you might be already working on "fio implementation" issue, once that you finish that, the next step is to enable the fio visualizer.

What is it?

FIO Visualizer is a GUI for the storage I/O performance measurement tool called FIO. It parses console output in real-time, displaying visual detail for IOPS, bandwidth and latency of each device's workload.  The data is gathered from FIO console output at assigned time intervals and updates the graphs immediately. It is especially valuable for benchmarking SSDs, particularly those based on NVMe specifications.

Key features:

```
* Real-time, continuously-updated FIO data in a visual graphic display.
* Customizable layout: a user can define which parameter(s) to monitor.
* Multi-thread + multi-job monitoring and support makes NVMe SSD benchmarking
```

 much easier.
    \* Base workload settings are used in all Intel SSD datasheets.
    \* Tool is multipurpose; it can be used for benchmarking and demo as a replacement
 to the deprecated Iometer tachometer window.
    \* Easy to use; it doesn’t require specific knowledge of software developing or 
scripting languages.
    \* Unique real-time QoS analytics.
    \* Written on Python with QtGraph; uses third-party libraries to simplify GUI code.

Important to know:

```
* FIO Visualizer is not a replacement for FIO; 
```

it simply outputs FIO data in an easy-to-read format.

All results should be posted here:
http://148.233.65.226/Linux_performance_tests_page/

**Comment by richo-mx** [comment]
@xe1gyq Are you interested in this issue ? seems like is not so popular as the other ones.

**Comment by jglezt** [comment]
I have already implemented the fio visualizer on my machine, but it seems buggy, I had to delete almost 90 lines to make it work, and some of the workload do not work, I will implement this on the server to find out if it just me. Just to inform about the progress of the visualizer :)

**Comment by richo-mx** [comment]
@helojagt Great !, could you please give us some clarifications?, what do you mean with buggy ? please describe in a very clear / short way the issue. by the other hand, if you have the fix, could you please upload the patches as RFC (first we need to understand what the issue was), thanks ! :)

**Comment by jglezt** [comment]
Ok, I already find out It just was me, on debian the version 0.8.9-1 of phyton-pyqtgraph It is not compatible whit the fio visualizer methods setStyle() and setLimit(), so is sure to dismiss the bug. I will report advances on the server soon :)

**Comment by richo-mx** [comment]
@helojagt , any advance with the work in the server side ? I'm just asking to see if we can close this isse already :)

**Comment by jglezt** [comment]
We are working whit the web plugging for the fio visualizer, it was delayed to have the first release ready :)

**Comment by richo-mx** [comment]
@helojagt Feel free to post any comment about the state of the current work, is important to keep all informed :+1:

**Comment by VictorRodriguez** [comment]
Need to check coherency but for me it works
